<a href="https://colab.research.google.com/github/DavidPPizarro/tensorflow/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install tensorflow tensorflow-gpu

In [7]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [8]:
import tensorflow as tf #impprt library tensorlow in a variable
print(tf.version) #print version of tensorlow

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.11/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Creating Tensors

In [9]:
stringtensor = tf.Variable("String tensor", tf.string)
number = tf.Variable(100, tf.int16)
floating = tf.Variable(100.0, tf.float64)

In [10]:
rank1_tensor = tf.Variable(["String", "Ok", "David"], tf.string) # one list
rank2_tensor = tf.Variable([["test", "ok"], ["test", "ok"]], tf.string) # two lists

Know the rank of the tensor

In [11]:
print(tf.rank(rank2_tensor))
print(tf.rank(rank1_tensor))
print(tf.rank(number))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


Tensor dimentions

In [18]:
print(rank1_tensor.shape)
print(rank2_tensor.shape)

(3,)
(2, 2)


**tf.ones(...): crea un tensor lleno de unos.**

[1, 2, 3]: define la forma del tensor, es decir, tendrá:

- 1 elemento en la primera dimensión
- 2 elementos en la segunda
- 3 elementos en la tercera

En total, el tensor tendrá 1 × 2 × 3 = 6 elementos.

**1. ¿Qué hace reshape?**
Reorganiza los elementos del tensor original en una nueva estructura sin modificar los datos subyacentes.

El tensor resultante (tensor2) tendrá el mismo número total de elementos que el original (producto de las dimensiones debe ser igual).

2. Forma (shape) [2, 3, 1]:

Esto define un tensor 3-dimensional con:
- 2 matrices (primera dimensión)
- 3 filas en cada matriz (segunda dimensión)
- 1 columna en cada fila (tercera dimensión)

**¿Qué significa [3, -1]?**:

-1 es un comodín que significa "calcula esta dimensión automáticamente para conservar el número total de elementos".

Cálculo:

- tensor2 original tiene 2 × 3 × 1 = 6 elementos.
- Nueva forma: [3, -1] → 3 × ? = 6 → ? = 2.
- Por lo tanto, -1 se reemplaza por 2, dando una forma final de [3, 2].

In [28]:
tensor1 = tf.ones([1, 2, 3])
#print(tensor1)
tensor2 = tf.reshape(tensor1, [2, 3, 1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor3)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


**Evaluando Tensores**

In [30]:
##La evaluación de Tensores fue eliminada ya que se hace de manera autmatica en la versión actual
# with tf.Session() as sess:
#   tensor.eval()


AttributeError: module 'tensorflow' has no attribute 'Session'

In [34]:
t = tf.zeros([5,5,5,5])
#print(t)
t = tf.reshape(t, [625])
#print(t)
t = tf.reshape(t, [125, -1])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]